#  makefile for DJGPP
#  Common Forth loader for GO32
#
#                                               Written by  : Luke Lee
#                                               Last update : 12/10/'95

CFLAGS = -c -g -fomit-frame-pointer

OUT =   cf.o \
	invokec.o \
	extended.o

LIB =   -lc -lg -lgpp -lgcc -lgpl -lm -lpc -lgrx

LNK =   -Wl,-Map,CF.MAP,-T,SECTIONS.LD

all: cf.o invokec.o extended.o cf.

cf.o:   cf.cc invokec.h
	gcc $(CFLAGS) cf.cc

invokec.o: invokec.cc invokec.h
	   gcc $(CFLAGS) invokec.cc

extended.o: extended.cc invokec.h
	   gcc $(CFLAGS) extended.cc

cf. :   $(OUT)
	gcc $(OUT) -o cf $(LIB) $(LNK)
	
cf.exe : cf.
	 bind cf
	 stubedit cf.exe keepmem=512k

