#
# Borland C++ IDE generated makefile
#
.AUTODEPEND


#
# Borland C++ tools
#
IMPLIB  = Implib
BCCD32     = Bcc32 +BccD32.cfg
TLINK32 = TLink32
TLIB    = TLib
TASM32  = Tasm32
#
# IDE macros
#


#
# Options
#
IDE_LFLAGSD32 =  -LK:\BC45\LIB
LLATD32_cfdexe =  -Tpe -ax -LK:\BC45\LIB
RLATD32_cfdexe = 
BLATD32_cfdexe = 
CNIEAT_cfdexe = -IK:\BC45\INCLUDE -D
LNIEAT_cfdexe = -x
LEAT_cfdexe = $(LLATD32_cfdexe)
REAT_cfdexe = $(RLATD32_cfdexe)
BEAT_cfdexe = $(BLATD32_cfdexe)

#
# Dependency List
#
Dep_cf = \
   cf.exe

cf : BccD32.cfg $(Dep_cf)
  echo MakeNode
  copy cf.exe turnkey.exe
  tdstrp32 turnkey.exe

Dep_cfdexe = \
   extended.obj\
   invokec.obj\
   cf.obj

cf.exe : $(Dep_cfdexe)
  $(TLINK32) @&&|
 /v $(IDE_LFLAGSD32) $(LEAT_cfdexe) $(LNIEAT_cfdexe) +
K:\BC45\LIB\c0x32.obj+
extended.obj+
invokec.obj+
cf.obj
$<,$*
K:\BC45\LIB\dpmi32.lib+
K:\BC45\LIB\bidsf.lib+
K:\BC45\LIB\tv32.lib+
K:\BC45\LIB\bgi32.lib+
K:\BC45\LIB\cw32.lib

|

extended.obj :  extended.cpp
  $(BCCD32) -c @&&|
 $(CEAT_cfdexe) $(CNIEAT_cfdexe) -o$@ extended.cpp
|

invokec.obj :  invokec.cpp
  $(BCCD32) -c @&&|
 $(CEAT_cfdexe) $(CNIEAT_cfdexe) -o$@ invokec.cpp
|

# Compiler configuration file
BccD32.cfg : 
   Copy &&|
-R
-v
-vi
-H
-H=cf.csm
-WX
| $@


