#  makefile for DJGPP
#  Common Forth loader for GO32
#
#						Written by  : Luke Lee
#						Last update : 12/10/'95

CFLAGS = -c -g

OUT =	cf.o \
	invokec.o \
	extended.o

LIB =   -lc -lg -lgpp -lgcc -lm -lpc -lgrx20

LNK =	-Wl,-Map,CF.MAP,-T,SECTIONS.LD

all: cf.o invokec.o extended.o cf.exe

cf.o:   cf.cc invokec.h
	gcc $(CFLAGS) cf.cc

invokec.o: invokec.cc invokec.h
	   gcc $(CFLAGS) invokec.cc

extended.o: extended.cc invokec.h
	   gcc $(CFLAGS) extended.cc

cf.exe : $(OUT) sections.ld
	gcc $(OUT) -o cf $(LIB) $(LNK)
	copy cf.exe turnkey.exe
	strip turnkey.exe

